update public.menu_categories
set is_active = false
where slug in ('coffee', 'non-coffee', 'dessert');

insert into public.menu_categories (
  slug,
  menu_type,
  name_ko,
  name_en,
  description,
  page_title,
  page_description,
  layout_variant,
  background_color,
  banner_image_url,
  banner_image_alt,
  sort_order,
  is_active
)
values
  ('coffee-highend', 'coffee', '하이앤드', 'HIGH END', '희소한 산지와 고급 품종 중심의 핸드드립 커피', 'HAND DRIP COFFEE', '전 메뉴 HOT/ICE 모두 가격 동일 (가격 단위 천원), 텀블러 이용 고객 500원 할인', 'list', '#EFF4F5', null, null, 10, true),
  ('coffee-nutty', 'coffee', '너티 (견과류, 고소한)', 'NUTTY', '견과류, 갈색 설탕, 초콜릿 계열의 편안한 커피', 'HAND DRIP COFFEE', '전 메뉴 HOT/ICE 모두 가격 동일 (가격 단위 천원), 텀블러 이용 고객 500원 할인', 'list', '#EFF4F5', null, null, 20, true),
  ('coffee-dark', 'coffee', '다크 (산미없는, 쌉사름한)', 'DARK', '묵직한 바디와 쌉싸름한 여운의 커피', 'HAND DRIP COFFEE', '전 메뉴 HOT/ICE 모두 가격 동일 (가격 단위 천원), 텀블러 이용 고객 500원 할인', 'list', '#EFF4F5', null, null, 30, true),
  ('coffee-fruity', 'coffee', '프루티 (과일향, 산미)', 'FRUITY', '화사한 산미와 과일 향미가 중심인 커피', 'HAND DRIP COFFEE', '전 메뉴 HOT/ICE 모두 가격 동일 (가격 단위 천원), 텀블러 이용 고객 500원 할인', 'list', '#EFF4F5', null, null, 40, true),
  ('coffee-milk', 'coffee', 'Coffee With Milk', 'COFFEE WITH MILK', '우유와 함께 즐기는 에스프레소 메뉴', 'HAND DRIP COFFEE', '전 메뉴 HOT/ICE 모두 가격 동일 (가격 단위 천원), 텀블러 이용 고객 500원 할인', 'list', '#EFF4F5', null, null, 50, true),
  ('non-coffee-main', 'non-coffee', 'NON-COFFEE', 'NON-COFFEE', '전 메뉴 HOT/ICE 모두 가격 동일 (가격 단위 천원)', 'NON-COFFEE', '전 메뉴 HOT/ICE 모두 가격 동일 (가격 단위 천원)', 'split-banners', '#FCFDF8', 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=1200&q=80', '아이스 말차 라떼', 10, true),
  ('non-coffee-tea', 'non-coffee', 'Tea', 'TEA', '전 메뉴 HOT/ICE 모두 가격 동일 (가격 단위 천원)', 'NON-COFFEE', '전 메뉴 HOT/ICE 모두 가격 동일 (가격 단위 천원)', 'split-banners', '#FCFDF8', 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1200&q=80', '티 음료', 20, true),
  ('non-coffee-hallabong', 'non-coffee', 'Hallabong Special', 'HALLABONG SPECIAL', '제주 한라봉을 이용한 스페셜 메뉴', 'NON-COFFEE', '전 메뉴 HOT/ICE 모두 가격 동일 (가격 단위 천원)', 'split-banners', '#FCFDF8', 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=1200&q=80', '감귤 음료', 30, true),
  ('non-coffee-ice', 'non-coffee', 'Ice cream & Shaved ice', 'ICE CREAM', '말차시럽 500원 추가', 'NON-COFFEE', '전 메뉴 HOT/ICE 모두 가격 동일 (가격 단위 천원)', 'split-banners', '#FCFDF8', 'https://images.unsplash.com/photo-1567206563064-6f60f40a2b57?auto=format&fit=crop&w=1200&q=80', '아이스크림', 40, true),
  ('dessert-bread', 'dessert', 'Bread / Sandwich', 'BREAD / SANDWICH', '빵, 샌드위치', 'DESSERT', '빵, 샌드위치와 매장 디저트', 'split-banners', '#FCFDF8', 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80', '브레드와 크로와상', 10, true),
  ('dessert-dessert', 'dessert', 'Dessert', 'DESSERT', null, 'DESSERT', '빵, 샌드위치와 매장 디저트', 'split-banners', '#FCFDF8', 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80', '케이크 디저트', 20, true)
on conflict (slug) do update
set menu_type = excluded.menu_type,
    name_ko = excluded.name_ko,
    name_en = excluded.name_en,
    description = excluded.description,
    page_title = excluded.page_title,
    page_description = excluded.page_description,
    layout_variant = excluded.layout_variant,
    background_color = excluded.background_color,
    banner_image_url = excluded.banner_image_url,
    banner_image_alt = excluded.banner_image_alt,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active;

with source_items as (
  select *
  from (
    values
      ('coffee-highend', 'P2', true, '파나마 라 에스메랄다 게이샤 마리오 아리바 4NC', 'Panama La Esmeralda Geisha Mario Arriba 4NC', null, '파인애플 / 스트로베리 / 실키 / 복합성 / 클린컵', '세계 최상위 게이샤 커피가 주는 복합적인 과일 향미와 깨끗한 컵을 경험해보세요.', '훌륭한 오케스트라의 합주를 듣는 듯한 감동을 주는 커피', 50.0, array['파인애플','스트로베리','실키','복합성','클린컵'], array['Pineapple','Strawberry','Silky','Complexity','Clean cup'], 'Volcan, Panama 볼칸, 파나마', 'La Esmeralda 라 에스메랄다', '1,650m', 'Geisha 게이샤', 'Cold room Natural 콜드룸 내추럴', 'Light - 2', '#ce9359', '#746191', 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1400&q=82', 'https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=1400&q=82', array['limited'], 'soldout', 10),
      ('coffee-highend', 'G2', true, '과테말라 엘 소코로 게이샤 워시드', 'Guatemala El Socorro Geisha Washed', null, '자스민 / 복숭아캔디 / 클린컵 / 은은한 여운', '엘 소코로 농장의 게이샤 워시드는 꽃향과 복숭아 캔디 같은 단맛이 은은하게 이어집니다.', '자스민과 복숭아 캔디의 향이 깨끗하게 이어지는 하이엔드 커피', 20.0, array['자스민','복숭아캔디','클린컵','은은한 여운'], array['Jasmine','Peach candy','Clean cup','Long finish'], 'Palencia, Guatemala 과테말라 팔렌시아', 'El Socorro 엘 소코로', '1,540m ~ 1,860m', 'Geisha 게이샤', 'Washed 워시드', 'Light - 2', '#73a491', '#945362', 'https://images.unsplash.com/photo-1511537190424-bbbab87ac5eb?auto=format&fit=crop&w=1400&q=82', 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1400&q=82', array[]::text[], 'available', 20),
      ('coffee-nutty', 'B5', true, '브라질 산타이네스 펄프드 내추럴', 'Brazil Santa Ines Pulped Natural', null, '아몬드 / 당밀 / 갈색설탕 / 오렌지', '전형적인 브라질 커피의 견과류 같은 고소함 뒤로 은은한 오렌지 산미가 좋은 커피입니다.', '아몬드와 갈색 설탕의 편안한 단맛이 좋은 커피', 7.0, array['아몬드','당밀','갈색설탕','오렌지'], array['Almond','Molasses','Brown sugar','Orange'], 'Minas Gerais, Brazil 미나스 제라이스, 브라질', 'Santa Ines 산타 이네스', '1,250m', 'Yellow Catuai 옐로우 카투아이', 'Pulped Natural 펄프드 내추럴', 'Medium', '#a1806b', '#e7c969', 'https://images.unsplash.com/photo-1515442261605-65987783cb6a?auto=format&fit=crop&w=1400&q=82', 'https://images.unsplash.com/photo-1502462041640-b3d7e50d0662?auto=format&fit=crop&w=1400&q=82', array[]::text[], 'available', 10),
      ('coffee-nutty', 'C5-0', true, '콜롬비아 수프리모 후일라 슈가케인 디카페인', 'Colombia Supremo Huila Sugarcane Decaf', null, '갈색 설탕 / 땅콩 버터 / 물엿', '사탕수수 유래 성분으로 카페인을 제거한 디카페인 커피입니다.', '시간대 상관없이 즐기기 좋은 고품질 디카페인 커피', 7.0, array['갈색 설탕','땅콩 버터','물엿'], array['Brown sugar','Peanut butter','Corn syrup'], 'Huila, Colombia 후일라, 콜롬비아', '-', '1,100m ~ 1,700m', 'Caturra, Castillo, Typica 카투라, 카스티요, 티피카', 'Sugarcane 슈가케인', 'Medium - 5', '#8b745d', '#7b774b', 'https://images.unsplash.com/photo-1512568400610-62da28bc8a13?auto=format&fit=crop&w=1400&q=82', 'https://images.unsplash.com/photo-1522992319-0365e5f11656?auto=format&fit=crop&w=1400&q=82', array[]::text[], 'available', 20),
      ('coffee-nutty', 'S4', true, '스테이 위드 피스', 'Stay With Peace Blend', null, '꽃 / 캐러멜 / 캐슈넛', '평화의 염원을 담은 블렌딩 커피입니다.', '꽃향과 캐러멜, 캐슈넛의 고소함이 균형 잡힌 블렌딩', 7.0, array['꽃','캐러멜','캐슈넛'], array['Floral','Caramel','Cashew nut'], 'Guatemala, Brazil, Ethiopia 과테말라, 브라질, 에티오피아', 'Stay With Peace 스테이 위드 피스', '-', '토종품종 / 레드 카투아이 / 옐로우 버번 / 카투라', 'Washed / Natural 워시드 / 내추럴', 'Medium', '#a59357', '#894938', 'https://images.unsplash.com/photo-1485808191679-5f86510681a2?auto=format&fit=crop&w=1400&q=82', 'https://images.unsplash.com/photo-1521302080334-4bebac2763a6?auto=format&fit=crop&w=1400&q=82', array['signature'], 'soldout', 30),
      ('coffee-dark', 'C7', true, '콜롬비아 카우카 리오 클라로 워시드', 'Colombia Cauca Rio Claro Washed', null, '다크 초콜릿 / 캐러멜 / 조청 / 자몽', '무게감 있는 다크 초콜릿 향미와 자몽의 산미가 어우러진 커피입니다.', '자몽을 감싼 다크초콜릿 한 조각 같은 커피', 7.0, array['다크 초콜릿','캐러멜','조청','자몽'], array['Dark chocolate','Caramel','Grain syrup','Grapefruit'], 'Cauca, Colombia 콜롬비아 카우카', 'Rio Claro 리오 클라로', '1,800m ~ 2,000m', 'Caturra, Colombia, Castillo 카투라, 콜롬비아, 카스티요', 'Washed 워시드', 'Dark', '#5b2d1f', '#694d2f', 'https://images.unsplash.com/photo-1525088553748-01d6e210e00b?auto=format&fit=crop&w=1400&q=82', 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?auto=format&fit=crop&w=1400&q=82', array[]::text[], 'available', 10),
      ('coffee-dark', 'I7', true, '인도네시아 만델링', 'Indonesia Mandheling', null, '젖은 흙향 / 삼나무 / 다크초콜릿', '수마트라 특유의 묵직한 바디와 길게 남는 애프터 테이스트가 매력적인 커피입니다.', '부드러운 단맛과 조화로운 바디감을 가진 커피', 7.0, array['젖은 흙향','삼나무','다크초콜릿'], array['Earthy','Cedar','Dark chocolate'], 'North Sumatra Tapanuli, Indonesia 북부 수마트라 타파눌리, 인도네시아', 'Small Farm Cooperative 소농 조합', '1,200m ~ 1,500m', 'Typica 티피카', 'Wet Hulled 웻 헐', 'Dark', '#3d3223', '#5b2d1f', 'https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1400&q=82', 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=1400&q=82', array[]::text[], 'available', 20),
      ('coffee-fruity', 'K6', true, '케냐 키리냐가 AA 워시드', 'Kenya Kirinyaga AA Washed', null, '블랙커런트 / 자몽 / 체리 / 실키', '케냐 특유의 생동감 있는 산미와 선명한 과일 향이 돋보이는 커피입니다.', '블랙커런트와 자몽의 산미가 선명한 커피', 8.0, array['블랙커런트','자몽','체리','실키'], array['Blackcurrant','Grapefruit','Cherry','Silky'], 'Kirinyaga, Kenya 케냐 키리냐가', 'Small Holders 소농민', '1,700m ~ 1,900m', 'SL28, SL34', 'Washed 워시드', 'Light - 3', '#894c5a', '#c7894c', 'https://images.unsplash.com/photo-1497636577773-f1231844b336?auto=format&fit=crop&w=1400&q=82', 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1400&q=82', array[]::text[], 'available', 10),
      ('coffee-fruity', 'E1-1', true, '에티오피아 시다마 아르베고나 보체사 워시드', 'Ethiopia Sidama Arbegona Bochessa Washed', null, '레몬그라스 / 복숭아 / 홍차 / 플로럴', '시다마 고지대의 청량한 산미와 꽃향이 섬세하게 느껴지는 커피입니다.', '레몬그라스와 복숭아, 홍차 향이 맑게 이어지는 커피', 8.0, array['레몬그라스','복숭아','홍차','플로럴'], array['Lemongrass','Peach','Black tea','Floral'], 'Sidama, Ethiopia 에티오피아 시다마', 'Bochessa 보체사', '2,000m ~ 2,300m', 'Ethiopian Heirloom 에티오피아 토종', 'Washed 워시드', 'Light - 1', '#7ab09c', '#9f5968', 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1400&q=82', 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1400&q=82', array[]::text[], 'available', 20),
      ('coffee-milk', 'M1', false, '플랫화이트', 'Flat White', null, '고소한 우유와 진한 에스프레소', '진한 에스프레소 위에 촘촘한 스팀 밀크를 더한 메뉴입니다.', '부드럽고 진한 밀크 커피', 6.0, array['우유','에스프레소','고소함'], array['Milk','Espresso','Nutty'], null, null, null, null, null, null, '#967d65', '#73a491', 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=1400&q=82', 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=1400&q=82', array['onlyhot'], 'available', 10),
      ('coffee-milk', 'M2', false, '오트크림 라떼', 'Oat Cream Latte', null, '오트 크림 / 라떼 / 부드러운 단맛', '오트의 고소함과 크림의 부드러움을 차갑게 즐기는 라떼입니다.', '오트 크림이 부드럽게 올라간 아이스 라떼', 7.0, array['오트','크림','라떼'], array['Oat','Cream','Latte'], null, null, null, null, null, null, '#9caa68', '#807e50', 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1400&q=82', 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=1400&q=82', array['onlyice'], 'available', 20),
      ('non-coffee-main', 'N1', false, '리얼 초코라떼', 'Real Chocolate Latte', null, null, '진한 초콜릿과 우유를 부드럽게 섞은 논커피 라떼입니다.', '진한 초콜릿의 밀도감이 있는 라떼', 6.5, array['초콜릿','우유'], array['Chocolate','Milk'], null, null, null, null, null, null, '#5b2d1f', '#967d65', 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=1400&q=82', null, array[]::text[], 'available', 10),
      ('non-coffee-main', 'N2', false, '제주 메밀 핫초코', 'Jeju Buckwheat Hot Chocolate', null, null, '제주 메밀의 구수함을 더한 따뜻한 핫초코입니다.', '구수한 제주 메밀 향이 감도는 핫초코', 6.0, array['초콜릿','메밀','따뜻함'], array['Chocolate','Buckwheat','Warm'], null, null, null, null, null, null, '#6f5846', '#d6ba66', 'https://images.unsplash.com/photo-1517578239113-b03992dcdd25?auto=format&fit=crop&w=1400&q=82', null, array['onlyhot'], 'available', 20),
      ('non-coffee-main', 'N3', false, '유기농 제주 말차라떼', 'Organic Jeju Matcha Latte', null, null, '유기농 제주 말차의 쌉싸름함과 우유의 단맛이 균형 잡힌 라떼입니다.', '유기농 제주 말차의 깊은 향을 담은 라떼', 7.0, array['말차','우유','쌉싸름함'], array['Matcha','Milk','Bittersweet'], null, null, null, null, null, null, '#5b6740', '#73a491', 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=1400&q=82', null, array[]::text[], 'available', 30),
      ('non-coffee-main', 'N4', false, '상하목장 아이스크림 제주말차라떼', 'Jeju Matcha Latte with Ice Cream', null, null, '말차 라떼 위에 상하목장 우유 아이스크림을 올린 메뉴입니다.', '말차와 우유 아이스크림의 진한 조합', 8.5, array['말차','아이스크림','우유'], array['Matcha','Ice cream','Milk'], null, null, null, null, null, null, '#41665b', '#d6ba66', 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1400&q=82', null, array[]::text[], 'available', 40),
      ('non-coffee-tea', 'T1', false, '피치 블로썸', 'Peach Blossom', '백차, 모과, 복숭아', null, '백차와 복숭아 향이 은은하게 이어지는 티 메뉴입니다.', '복숭아 향과 백차의 맑은 여운', 7.0, array['백차','모과','복숭아'], array['White tea','Quince','Peach'], null, null, null, null, null, null, '#d18077', '#9f5968', 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1400&q=82', null, array[]::text[], 'available', 10),
      ('non-coffee-tea', 'T2', false, '자스민 그린', 'Jasmine Green', '녹차, 자스민꽃', null, '녹차의 산뜻함에 자스민꽃 향을 더했습니다.', '자스민꽃 향이 맑게 올라오는 녹차', 7.0, array['녹차','자스민꽃'], array['Green tea','Jasmine flower'], null, null, null, null, null, null, '#7ab09c', '#a8b773', 'https://images.unsplash.com/photo-1563911892437-1feda0179e1b?auto=format&fit=crop&w=1400&q=82', null, array[]::text[], 'available', 20),
      ('non-coffee-hallabong', 'H1', false, '제주 한라봉차', 'Jeju Hallabong Tea', null, null, '제주 한라봉의 향과 단맛을 따뜻하게 즐기는 차입니다.', '한라봉의 향긋한 단맛을 담은 차', 7.0, array['한라봉','감귤','따뜻함'], array['Hallabong','Citrus','Warm'], null, null, null, null, null, null, '#dd9d5b', '#d6ba66', 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=1400&q=82', null, array[]::text[], 'available', 10),
      ('non-coffee-hallabong', 'H2', false, '제주 한라봉 스무디', 'Jeju Hallabong Smoothie', null, null, '한라봉의 산뜻함을 차갑고 부드럽게 즐기는 스무디입니다.', '상큼하고 부드러운 한라봉 스무디', 7.0, array['한라봉','스무디','상큼함'], array['Hallabong','Smoothie','Refreshing'], null, null, null, null, null, null, '#c7894c', '#7ab09c', 'https://images.unsplash.com/photo-1502741224143-90386d7f8c82?auto=format&fit=crop&w=1400&q=82', null, array[]::text[], 'available', 20),
      ('non-coffee-hallabong', 'H3', false, '제주 한라봉 에이드', 'Jeju Hallabong Ade', null, null, '탄산감과 한라봉의 산미가 시원하게 어우러지는 에이드입니다.', '한라봉의 산미를 청량하게 즐기는 에이드', 8.0, array['한라봉','탄산','청량함'], array['Hallabong','Sparkling','Crisp'], null, null, null, null, null, null, '#dd9d5b', '#73a491', 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?auto=format&fit=crop&w=1400&q=82', null, array[]::text[], 'available', 30),
      ('non-coffee-ice', 'I1', false, '상하목장 우유아이스크림', 'Sangha Milk Ice Cream', null, null, '진한 우유 풍미가 느껴지는 부드러운 아이스크림입니다.', '진한 우유 풍미의 아이스크림', 6.5, array['우유','아이스크림'], array['Milk','Ice cream'], null, null, null, null, null, null, '#967d65', '#d6ba66', 'https://images.unsplash.com/photo-1567206563064-6f60f40a2b57?auto=format&fit=crop&w=1400&q=82', null, array[]::text[], 'available', 10),
      ('dessert-bread', 'D1', false, '모닝세트', 'Morning Set', '잠봉 베이글 샌드위치 + 핸드드립커피', null, '든든한 잠봉 베이글 샌드위치와 핸드드립 커피를 함께 즐기는 세트입니다.', '아침에 잘 어울리는 샌드위치와 커피 세트', 14.5, array['잠봉','베이글','핸드드립'], array['Jambon','Bagel','Hand drip'], null, null, null, null, null, null, '#967d65', '#a8b773', 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=1400&q=82', null, array['best'], 'available', 10),
      ('dessert-bread', 'D2', false, '브런치세트', 'Brunch Set', '잠봉뵈르 크로와상 샌드위치 + 핸드드립 커피', null, '버터 풍미가 좋은 크로와상 샌드위치와 핸드드립 커피 세트입니다.', '크로와상 샌드위치와 커피를 함께 즐기는 브런치 세트', 14.5, array['크로와상','잠봉뵈르','핸드드립'], array['Croissant','Jambon beurre','Hand drip'], null, null, null, null, null, null, '#a1806b', '#d6ba66', 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1400&q=82', null, array['best'], 'available', 20),
      ('dessert-bread', 'D3', false, '뱅오쇼콜라', 'Pain au Chocolat', null, null, '바삭한 결 사이로 초콜릿 풍미가 느껴지는 페이스트리입니다.', '초콜릿을 품은 프렌치 페이스트리', 3.8, array['초콜릿','페이스트리','버터'], array['Chocolate','Pastry','Butter'], null, null, null, null, null, null, '#5b2d1f', '#d6ba66', 'https://images.unsplash.com/photo-1623334044303-241021148842?auto=format&fit=crop&w=1400&q=82', null, array[]::text[], 'available', 30),
      ('dessert-bread', 'D4', false, '잠봉 베이글 샌드위치', 'Jambon Bagel Sandwich', null, null, '쫄깃한 베이글에 잠봉과 버터를 더한 샌드위치입니다.', '짭조름한 잠봉과 베이글의 든든한 조합', 9.5, array['잠봉','베이글','버터'], array['Jambon','Bagel','Butter'], null, null, null, null, null, null, '#967d65', '#894938', 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=1400&q=82', null, array[]::text[], 'available', 40),
      ('dessert-dessert', 'DS1', false, '쑥 티라미수 케이크', 'Mugwort Tiramisu Cake', null, null, '쑥의 은은한 향과 크림의 부드러움이 어우러진 케이크입니다.', '쑥 향이 은은하게 퍼지는 티라미수 케이크', 7.8, array['쑥','크림','티라미수'], array['Mugwort','Cream','Tiramisu'], null, null, null, null, null, null, '#5b6740', '#967d65', 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1400&q=82', null, array[]::text[], 'available', 10),
      ('dessert-dessert', 'DS2', false, '한라봉 치즈테린느', 'Hallabong Cheese Terrine', null, null, '한라봉의 산뜻함을 더한 진한 치즈 테린느입니다.', '한라봉 산미와 치즈의 농도가 만나는 디저트', 6.0, array['한라봉','치즈','테린느'], array['Hallabong','Cheese','Terrine'], null, null, null, null, null, null, '#dd9d5b', '#967d65', 'https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?auto=format&fit=crop&w=1400&q=82', null, array[]::text[], 'available', 20),
      ('dessert-dessert', 'DS3', false, '제주 유기농 말차테린느', 'Organic Jeju Matcha Terrine', null, null, '유기농 제주 말차의 진한 향을 담은 테린느입니다.', '쌉싸름한 말차 향이 짙은 테린느', 6.0, array['말차','테린느','제주'], array['Matcha','Terrine','Jeju'], null, null, null, null, null, null, '#5b6740', '#41665b', 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=1400&q=82', null, array[]::text[], 'available', 30),
      ('dessert-dessert', 'DS4', false, '수제 한라봉 초콜릿', 'Handmade Hallabong Chocolate', '직접 갈아 넣은 유기농 제주산 한라봉이 씹히는 수제 초콜릿', null, '한라봉 껍질과 과육의 향을 초콜릿에 더했습니다.', '한라봉 향이 씹히는 수제 초콜릿', 2.9, array['한라봉','초콜릿','수제'], array['Hallabong','Chocolate','Handmade'], null, null, null, null, null, null, '#5b2d1f', '#dd9d5b', 'https://images.unsplash.com/photo-1548907040-4d2be7f51521?auto=format&fit=crop&w=1400&q=82', null, array[]::text[], 'available', 40)
  ) as item(category_slug, code, display_code, name_ko, name_en, subtitle, summary, description, detail_highlight, price, flavor_notes, flavor_notes_en, origin, farm, altitude, variety, processing, roasting_point, main_flavor_color, sub_flavor_color, image_url, detail_image_url, badges, status, sort_order)
)
insert into public.menu_items (
  category_id,
  code,
  display_code,
  name_ko,
  name_en,
  subtitle,
  summary,
  description,
  detail_title,
  detail_body,
  detail_highlight,
  price,
  flavor_notes,
  flavor_notes_en,
  origin,
  farm,
  altitude,
  variety,
  processing,
  roasting_point,
  main_flavor_color,
  sub_flavor_color,
  image_url,
  detail_image_url,
  badges,
  status,
  sort_order,
  is_published
)
select
  c.id,
  s.code,
  s.display_code,
  s.name_ko,
  s.name_en,
  s.subtitle,
  s.summary,
  s.description,
  coalesce(s.code || '. ', '') || s.name_ko,
  s.description,
  s.detail_highlight,
  s.price,
  s.flavor_notes,
  s.flavor_notes_en,
  s.origin,
  s.farm,
  s.altitude,
  s.variety,
  s.processing,
  s.roasting_point,
  s.main_flavor_color,
  s.sub_flavor_color,
  s.image_url,
  s.detail_image_url,
  s.badges,
  s.status,
  s.sort_order,
  true
from source_items s
join public.menu_categories c on c.slug = s.category_slug
on conflict (category_id, code) do update
set display_code = excluded.display_code,
    name_ko = excluded.name_ko,
    name_en = excluded.name_en,
    subtitle = excluded.subtitle,
    summary = excluded.summary,
    description = excluded.description,
    detail_title = excluded.detail_title,
    detail_body = excluded.detail_body,
    detail_highlight = excluded.detail_highlight,
    price = excluded.price,
    flavor_notes = excluded.flavor_notes,
    flavor_notes_en = excluded.flavor_notes_en,
    origin = excluded.origin,
    farm = excluded.farm,
    altitude = excluded.altitude,
    variety = excluded.variety,
    processing = excluded.processing,
    roasting_point = excluded.roasting_point,
    main_flavor_color = excluded.main_flavor_color,
    sub_flavor_color = excluded.sub_flavor_color,
    image_url = excluded.image_url,
    detail_image_url = excluded.detail_image_url,
    badges = excluded.badges,
    status = excluded.status,
    sort_order = excluded.sort_order,
    is_published = excluded.is_published;
